name: swc-climatedata
channels:
    - scitools
    - ioam
dependencies:
    - python=3
    - pytest
    - jupyter
    - xarray
    - dask
    - iris
    - cartopy
    - protobuf
    - holoviews
    - geoviews
    - pip:
        - siphon
